const Bow = [
	{
		 Type: "Bow"
		,Name: "Bow"
		,Attack_Power: 11
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 5.85
		,Atk_Speed: 0.65
		,Title: "Bow\n\nAttack Power +11"
		,Rarity: "Common"
	}
	,{
		 Type: "Bow"
		,Name: "Wooden_Bow"
		,Attack_Power: 26
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 5.85
		,Atk_Speed: 0.65
		,Title: "Wooden_Bow\n\nAttack Power +26"
		,Rarity: "Uncommon"
	}
	,{
		 Type: "Bow"
		,Name: "Longbow"
		,Attack_Power: 25
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 5.85
		,Atk_Speed: 0.65
		,Title: "Longbow\n\nAttack Power +25"
		,Rarity: "Uncommon"
	}
	,{
		 Type: "Bow"
		,Name: "Composite_Bow"
		,Attack_Power: 16
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 5.85
		,Atk_Speed: 0.65
		,Title: "Composite Bow\n\nAttack Power +16\nHealing Reduction (Normal Attacks) -40%"
		,Rarity: "Rare"
	}
	,{
		 Type: "Bow"
		,Name: "Strong_Bow"
		,Attack_Power: 26
		,Attack_Speed: 15
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 5.85
		,Atk_Speed: 0.65
		,Title: "Strong Bow\n\nAttack Power +26\nAttack Speed +15%"
		,Rarity: "Rare"
	}
	,{
		 Type: "Bow"
		,Name: "Stallion_Bow"
		,Attack_Power: 20
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 25
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 5.85
		,Atk_Speed: 0.65
		,Title: "Stallion Bow\n\nAttack Power +20\nExtra Normal Attack Damage +25"
		,Rarity: "Rare"
	}
	,{
		 Type: "Bow"
		,Name: "Mighty_Bow"
		,Attack_Power: 20
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 11
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 5.85
		,Atk_Speed: 0.65
		,Title: "Mighty Bow\n\nAttack Power +20\nExtra Normal Attack Damage +11"
		,Rarity: "Rare"
	}
	,{
		 Type: "Bow"
		,Name: "Pellet_Bow"
		,Attack_Power: 55
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 5.85
		,Atk_Speed: 0.65
		,Title: "Pellet Bow\n\nAttack Power +55"
		,Rarity: "Rare"
	}
	,{
		 Type: "Bow"
		,Name: "Scorchbow"
		,Attack_Power: 24
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 18
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 5.85
		,Atk_Speed: 0.65
		,Title: "Scorchbow\n\nAttack Power +24\nSkill Amplification +18"
		,Rarity: "Rare"
	}
	,{
		 Type: "Bow"
		,Name: "Ancient_Bolt"
		,Attack_Power: 55
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 40
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 5.85
		,Atk_Speed: 0.65
		,Title: "Ancient Bolt\n\nAttack Power +55\nExtra Normal Attack Damage +40"
		,Rarity: "Epic"
	}
	,{
		 Type: "Bow"
		,Name: "Golden-Ratio_Bow"
		,Attack_Power: 68
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 20
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 5.85
		,Atk_Speed: 0.65
		,Title: "Golden-Ratio Bow\n\nAttack Power +68\nSkill Amplification +20%"
		,Rarity: "Epic"
	}
	,{
		 Type: "Bow"
		,Name: "Twinbow"
		,Attack_Power: 70
		,Attack_Speed: 50
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 5.85
		,Atk_Speed: 0.65
		,Title: "Twinbow\n\nAttack Power +70\nAttack Speed +50%\nHealing Reduction (Normal Attacks) -40%"
		,Rarity: "Epic"
	}
	,{
		 Type: "Bow"
		,Name: "Elemental_Bow"
		,Attack_Power: 60
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 41
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 5.85
		,Atk_Speed: 0.65
		,Title: "Elemental Bow\n\nAttack Power +60\nMovement Speed +0.1\nSkill Amplification +41\nHealing Reduction (Skills) -40%"
		,Rarity: "Epic"
	}
	,{
		 Type: "Bow"
		,Name: "Failnaught"
		,Attack_Power: 90
		,Attack_Speed: 15
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 15
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 5.85
		,Atk_Speed: 0.65
		,Title: "Failnaught\n\nAttack Power +90\nAttack Speed +15%\nLife Steal +15%"
		,Rarity: "Legendary"
	}
];