const Accessory = [
    {
         Type: "Accessory"
        ,Name: "Feather"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0.08
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Feather\n\nMovement Speed +0.08"
        ,Rarity: "Common"
    }
    ,{
         Type: "Accessory"
        ,Name: "Flower"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 7
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Flower\n\nCooldown Reduction +7%"
        ,Rarity: "Common"
    }
    ,{
         Type: "Accessory"
        ,Name: "Ribbon"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 5
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Ribbon\n\nLife Steal +5%"
        ,Rarity: "Common"
    }
    ,{
         Type: "Accessory"
        ,Name: "Fan"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 11
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Fan\n\nSkill Amplification +11"
        ,Rarity: "Common"
    }
    ,{
         Type: "Accessory"
        ,Name: "Buddhist_Scripture"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 7
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Buddhist Scripture\n\nSkill Amplification +7%"
        ,Rarity: "Common"
    }
    ,{
         Type: "Accessory"
        ,Name: "Box"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 90
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Box\n\nMax HP +90"
        ,Rarity: "Common"
    }
    ,{
         Type: "Accessory"
        ,Name: "Holy_Grail"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 120
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Holy Grail\n\nHP Regen +120%"
        ,Rarity: "Common"
    }
    ,{
         Type: "Accessory"
        ,Name: "Cross"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 7
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Cross\n\nExtra Normal Attack Damage +7"
        ,Rarity: "Common"
    }
    ,{
         Type: "Accessory"
        ,Name: "Binoculars"
        ,Attack_Power: 2
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 1.5
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Binoculars\n\nAttack Power +2\nVision Range +1.5"
        ,Rarity: "Common"
    }
    ,{
         Type: "Accessory"
        ,Name: "Saint`s_Relic"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 8
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 150
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Saint`s Relic\n\nHP Regen +150%\nExtra Normal Attack Damage +8"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Accessory"
        ,Name: "Flower_of_Fate"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 15
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 10
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Flower of Fate\n\nCritical Strike Chance +15%\nCooldown Reduction +10%"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Accessory"
        ,Name: "Glass_Pieces"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 13
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Glass Pieces\n\nCritical Strike Chance +13%"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Accessory"
        ,Name: "Doll"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 11
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 100
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Doll\n\nSP Regen +100%\nLife Steal +11%"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Accessory"
        ,Name: "Sniping_Scope"
        ,Attack_Power: 6
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 4
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Sniper Scope\n\nAttack Power +6\nVision Range +4"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Accessory"
        ,Name: "Buddha_Sarira"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 8
        ,Cooldown_Reduction: 8
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Buddha Sarira\n\nCooldown Reduction +8%\nSkill Amplification +8%"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Accessory"
        ,Name: "Quiver"
        ,Attack_Power: 0
        ,Attack_Speed: 22
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Quiver\n\nAttack Speed +22%"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Accessory"
        ,Name: "Feather_Duster"
        ,Attack_Power: 9
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Feather Duster\n\nAttack Power +9\nMovement Speed +0.1"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Accessory"
        ,Name: "Gilded_Quill_Fan"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 14
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Gilded Quill Fan\n\nSkill Amplification +14\nHealing Reductions (Skills) -40%"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Accessory"
        ,Name: "Shaman`s_Bronze"
        ,Attack_Power: 5
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 8
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Shaman`s Bronze\n\nAttack Power +5\nSkill Amplification +8%"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Accessory"
        ,Name: "White_Crane_Fan"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 16
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "White Crane Fan\n\nMovement Speed +0.1\nSkill Amplification +16\nHealing Reduction (Skills) -40%"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Accessory"
        ,Name: "Powder_of_Life"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 1.5
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 1.5
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Powder of Life\n\nHP Regen +1.5\nSP Regen +1.5"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Accessory"
        ,Name: "Uchiwa"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 15
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 21
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 100
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Uchiwa\n\nSP Regen +100%\nLife Steal +15%\nSkill Amplification +21"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Accessory"
        ,Name: "Magazine"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 350
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 6
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Magazine\n\nMax HP +350\nNormal Attack Damage Reduction +6"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Accessory"
        ,Name: "Laced_Quiver"
        ,Attack_Power: 10
        ,Attack_Speed: 30
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Laced Quiver\n\nAttack Power +10\nAttack Speed +30%\nMovement Speed +0.1"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Accessory"
        ,Name: "Revenge_of_Goujian"
        ,Attack_Power: 10
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 20
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Revenge of Goujian\n\nAttack Power +10\nSkill Amplification +20%"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Accessory"
        ,Name: "Moonlight_Pendant"
        ,Attack_Power: 20
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 20
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Moonlight Pendant\n\nAttack Power +20\nLife Steal +20%"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Accessory"
        ,Name: "Schrodinger`s_Box"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 7
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 420
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Schrodinger`s Box\n\nMax HP +420\nSkill Amplification +7"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Accessory"
        ,Name: "Veritas_Lux_Mea"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 12
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 8
        ,Cooldown_Reduction: 10
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 150
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Veritas Lux Mea\n\nHP Regen +150%\nCooldown Reduction +10%\nExtra Normal Attack Damage +12\nSkill Amplification +8%"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Accessory"
        ,Name: "Glacial_Ice"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 18
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 1.5
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 1.5
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Glacial Ice\n\nHP Regen +1.5\nSP Regen +1.5\n Skill Amplification +18"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Accessory"
        ,Name: "True_Samadhi_Fire"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 13
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 1.5
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 1.5
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "True Samadhi Fire\n\nHP Regen +1.5\nSP Regen +1.5\nExtra Normal Attack Damage +13"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Accessory"
        ,Name: "Emerald_Tablet"
        ,Attack_Power: 10
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 15
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 10
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 10
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Emerald Tablet\n\nAttack Power +10\nDefense +10\nCritical Strike Chance +15%\nCooldown Reduction +10%"
        ,Rarity: "Legendary"
    }
];