const Arm = [
    {
         Type: "Arm"
        ,Name: "Watch"
        ,Attack_Power: 0
        ,Attack_Speed: 10
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Watch\n\nAttack Speed +10%"
        ,Rarity: "Common"
    }
    ,{
         Type: "Arm"
        ,Name: "Bandage"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0.8
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Bandage\n\nHP Regen +0.8"
        ,Rarity: "Common"
    }
    ,{
         Type: "Arm"
        ,Name: "Bracelet"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 220
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Bracelet\n\nMax SP +220"
        ,Rarity: "Common"
    }
    ,{
         Type: "Arm"
        ,Name: "Leather_Shield"
        ,Attack_Power: 10
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 10
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Leather Shield\n\nAttack Power +10\nDefense +10"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Arm"
        ,Name: "Squad_Leader_Armband"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 15
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 1.5
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Squad Leader Armband\n\nHP Regen +1.5\nCritical Damage +15%"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Arm"
        ,Name: "Bracer"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 13
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 1
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Bracer\n\nDefense +13\nHP Regen +1"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Arm"
        ,Name: "Sheath"
        ,Attack_Power: 18
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 2
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Sheath\n\nAttack Power +18\nNormal Attack Damage Reduction +2"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Arm"
        ,Name: "Golden_Bracelet"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 12
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 220
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Golden Bracelet\n\nMax SP +220\nSkill Amplification +12%"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Arm"
        ,Name: "Bazuband"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 25
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 8
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Bazuband\n\nDefense +25\nNormal Attack Damage Reduction +8"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Arm"
        ,Name: "Crimson_Bracelet"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 200
        ,Max_SP: 250
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Crimson Bracelet\n\nMax HP +200\nMax SP +250"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Arm"
        ,Name: "Steel_Shield"
        ,Attack_Power: 23
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 20
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: -0.05
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Steel Shield\n\nAttack Power +23\nDefense +20\nMovement Speed -0.05"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Arm"
        ,Name: "Cube_Watch"
        ,Attack_Power: 0
        ,Attack_Speed: 50
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 27
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Cube Watch\n\nDefense +27\nAttack Speed +50%"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Arm"
        ,Name: "Sword_Stopper"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 32
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 11
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Sword Stopper\n\nDefense +32\nNormal Attack Damage Reduction +11\nHealing Reduction (Normal Attacks) -40%"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Arm"
        ,Name: "Draupnir"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 15
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 10
        ,Max_HP: 0
        ,Max_SP: 240
        ,HP_Regen: 1
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Draupnir\n\nDefense +10\nMax HP +240\nHP Regen +1\n Skill Amplification +15%"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Arm"
        ,Name: "Mithril_Shield"
        ,Attack_Power: 30
        ,Attack_Speed: 12
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 30
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Mithril Shield\n\nAttack Power +30\nDefense +30\nAttack Speed +12%\nMovement Speed +0.1"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Arm"
        ,Name: "Vital_Sign_Sensor"
        ,Attack_Power: 0
        ,Attack_Speed: 30
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 15
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Vital Sign Sensor\n\nDefense +15\nAttack Speed +30%"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Arm"
        ,Name: "Creed_of_the_Knight"
        ,Attack_Power: 30
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 20
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 20
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 1.5
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: -0.05
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Creed pf the Knight\n\nAttack Power +30\nDefense +20\nHP Regen +1.5\nMovement Speed -0.05\nCritical Damage +20%"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Arm"
        ,Name: "Sword_of_Shah_Jahan"
        ,Attack_Power: 25
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 300
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 2
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Sword of Shah Jahan\n\nAttack Power +25\nMax HP +300\nNormal Attack Damage Reduction +2"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Arm"
        ,Name: "Bracelet_of_Skadi"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 20
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 2
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 200
        ,Max_SP: 250
        ,HP_Regen: 2
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Bracelet of Skadi\n\nMax HP +200\nMax SP +250\nHP Regen +2\nSP Regen +2\nSkill Amplification +20"
        ,Rarity: "Legendary"
    }
    ,{
         Type: "Arm"
        ,Name: "Radar"
        ,Attack_Power: 0
        ,Attack_Speed: 40
        ,Critical_Strike_Chance: 20
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 15
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Radar\n\nDefense +15\nAttack Speed +40%\nCritical Strike Chance +20%"
        ,Rarity: "Legendary"
    }
    ,{
         Type: "Arm"
        ,Name: "Auto-arms"
        ,Attack_Power:40
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 35
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 1.5
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Auto-arms\n\nAttack Power +40\nDefense +35\nHP Regen +1.5"
        ,Rarity: "Legendary"
    }
];