const Chest = [
    {
         Type: "Chest"
        ,Name: "Windbreaker"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 50
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 3
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Windbreaker\n\nMax HP +50\nNormal Attack Damage Reduction +3"
        ,Rarity: "Common"
    }
    ,{
         Type: "Chest"
        ,Name: "Monk`s_Robe"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 5
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 5
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Monk`s Robe\n\nDefense +5\nCooldown Reduction +5%"
        ,Rarity: "Common"
    }
    ,{
         Type: "Chest"
        ,Name: "Wetsuit"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 5
        ,Defense: 1
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 3
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Wetsuit\n\nDefense +1\nSkill Damage Reduction +5%"
        ,Rarity: "Common"
    }
    ,{
         Type: "Chest"
        ,Name: "Fabric_Armor"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 11
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Fabric Armor\n\nDefense +11"
        ,Rarity: "Common"
    }
    ,{
         Type: "Chest"
        ,Name: "Leather_Armor"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 22
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Leather Armor\n\nDefense +22"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Chest"
        ,Name: "Leather_Jacker"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 8
        ,Max_HP: 70
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 6
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Leather Jacket\n\nDefense +8\nMax HP +70\nNormal Attack Damage Reduction +6"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Chest"
        ,Name: "Turtle_Dobok"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 10
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 10
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Turtle Donok\n\nDefense +10\nCooldown Reduction +10%"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Chest"
        ,Name: "Military_Suit"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 50
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 10
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Military Suit\n\nMax HP +50\nNormal Attack Damage Reduction +10"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Chest"
        ,Name: "Patched_Robe"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 7
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 5
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 1
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 3
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Patched Robe\n\nDefense +5\nHP Regen +1\nCooldown Reduction +7%"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Chest"
        ,Name: "Dress"
        ,Attack_Power: 8
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 100
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 8
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Dress\n\nAttack Power +8\nDefense +8\nSP Regen +100%"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Chest"
        ,Name: "Bikini"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 11
        ,Defense: 4
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Bikini\n\nDefense +4\nSkill Damage Reduction +11%"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Chest"
        ,Name: "Diving_Suit"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 10
        ,Defense: 9
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Diving Suit\n\nDefense +9\nSkill Damage Reduction +10%"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Chest"
        ,Name: "Rider_Jacket"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 11
        ,Max_HP: 70
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 9
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Rider Jacket\n\nDefense +11\nMax HP +70\nNormal Attack Damage Reduction +9"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Chest"
        ,Name: "Chain_Armor"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 30
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Chain Armor\n\nDefense +30"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Chest"
        ,Name: "Suit"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 5
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 12
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Suit\n\nLife Steal +5\nNormal Attack Damage Reduction +12"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Chest"
        ,Name: "Qipao"
        ,Attack_Power: 10
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 150
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 10
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Qipao\n\nAttack Power +10\nDefense +10\nSP Regen +150%"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Chest"
        ,Name: "Sheet_Metal_Armor"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 38
        ,Max_HP: 100
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: -0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Sheet Metal Armor\n\nDefense +38\nMax HP +100\nMovement Speed - 0.1"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Chest"
        ,Name: "Hanbok"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 8
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 12
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 1
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Hanbok\n\nDefense +12\nHP Regen +1\nCooldown Reduction +8%"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Chest"
        ,Name: "Bulletproof_Vest"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 10
        ,Max_HP: 130
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 10
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Bulletproof Vest\n\nDefense +10\nMax HP +130\nNormal Attack Damage Reduction +10"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Chest"
        ,Name: "Sunset_Armor"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 28
        ,Max_HP: 450
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Sunset Armor\n\nDefense +28\nMax HP +450"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Chest"
        ,Name: "Covert_Agent_Uniform"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 15
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 23
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 2.5
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Convert Agent Uniform\n\nDefense +23\nHP Regen +2.5\nCooldown Reduction +15%"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Chest"
        ,Name: "Optical_Camouflage_Suit"
        ,Attack_Power: 10
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 22
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 10
        ,Defense: 20
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Optical Camouflage Suit\n\nAttack Power +10\nDefense +20\nCritical Strike Chance +22%\nSkill Damage Reduction +10%"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Chest"
        ,Name: "Rocker`s_Jacket"
        ,Attack_Power: 30
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 11
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 11
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0.15
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Rocker`s Jacket\n\nAttack Power +30\nDefense +11\nMovement speed while not in combat +0.15\nNormal Attack Damage Reduction +11\nHealing Reduction (Skills) -40%"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Chest"
        ,Name: "Mithril_Armor"
        ,Attack_Power: 0
        ,Attack_Speed: 12
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 65
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0.2
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Mithril Armor\n\nDefense +65\nAttack Speed +12%\n Movement Speed +0.2"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Chest"
        ,Name: "Crusader_Armor"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 15
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 30
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 200
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: -0.02
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Crusader Armor\n\nDefense +30\nHP Regen +200%\nMovement Speed - 0.02\nExtra Damage to Normal Attacks +15"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Chest"
        ,Name: "Amazoness_Armor"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 20
        ,Defense: 28
        ,Max_HP: 120
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Amazoness Armor\n\nDefense +28\nMax HP +120\nSkill Damage Reduction +20%"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Chest"
        ,Name: "Dragon_Dobok"
        ,Attack_Power: 11
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 10
        ,SP_Regen: 0
        ,SP_Regen_Percent: 150
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 10
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 3
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 1
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Dragon Dobok\n\nAttack Power +11\nDefense +10\nSP Regen +150%\nCooldown Reduction +10%\nAttack Range +1"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Chest"
        ,Name: "Commander`s_Armor"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 16
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 20
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Commander`s Armor\n\nDefense +20\nSkill Damage Increase +18%"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Chest"
        ,Name: "Butler`s_Suit"
        ,Attack_Power: 30
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 20
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 10
        ,Move_Speed: 0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Butler`s Suit\n\nAttack Power +30\nMovement Speed +0.1\nLife Steal +20%\nNormal Attack Damage Reduction +10"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Chest"
        ,Name: "Battle_Suit"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 12
        ,Defense: 25
        ,Max_HP: 140
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 12
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Battle Suit\n\nDefense +25\nMax HP +140\nNormal Attack Damage Reduction +12\nSkill Damage Reduction +12%"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Chest"
        ,Name: "EOD_Suit"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 10
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 15
        ,Max_HP: 300
        ,Max_SP: 0
        ,HP_Regen: 1
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 12
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "EPD Siot\n\nDefense +15\nMax HP +300\nHP Regen +1\nCooldown Reduction +10%\nNormal Attack Damage Reduction +12"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Chest"
        ,Name: "Blazing_Dress"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 18
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 3
        ,SP_Regen_Percent: 75
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 25
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 2.5
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Blazing Dress\n\nDefense +25\nHP Regen +2.5\nSP Regen +3\nSP Regen +75%\nExtra Normal Attack Damage +18"
        ,Rarity: "Legendary"
    }
    ,{
         Type: "Chest"
        ,Name: "Kabana"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 20
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 36
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Kabana\n\nDefense +36\nSkill Amplification +20%"
        ,Rarity: "Legendary"
    }
    ,{
         Type: "Chest"
        ,Name: "Queen_of_Hearts"
        ,Attack_Power: 0
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 25
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 45
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 3
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0
        ,Atk_Speed: 0
        ,Title: "Queen of Hearts\n\nDefense +45\nHP Regen +3\nCooldown Reduction +25%"
        ,Rarity: "Legendary"
    }
];