const heads = [
	{
		 Type: "Head"
		,Name: "Hairband"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 4
		,Max_HP: 0
		,Max_SP: 130
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Hairband\n\nDefense +4\nMax SP +130"
		,Rarity: "Common"
	}
	,{
		 Type: "Head"
		,Name: "Hat"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 5
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 4
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Hat\n\nDefense +4\nCooldown Reduction +5%"
		,Rarity: "Common"
	}
	,{
		 Type: "Head"
		,Name: "Bike_Helmet"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 90
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Bike Helmet\n\nMax HP +90"
		,Rarity: "Common"
	}
	,{
		 Type: "Head"
		,Name: "Mask"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 10
		,Max_HP: 0
		,Max_SP: 130
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.08
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Mask\n\nDefense +10\nMax SP +130\nMovement Speed +0.08"
		,Rarity: "Uncommon"
	}
	,{
		 Type: "Head"
		,Name: "Circlet"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 14
		,Max_HP: 0
		,Max_SP: 270
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Circlet\n\nDefense +14\nMax SP +270"
		,Rarity: "Uncommon"
	}
	,{
		 Type: "Head"
		,Name: "Beret"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 7
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 10
		,Max_HP: 60
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Beret\n\nDefense +10\nMax HP +60\nCooldown Reduction +7%"
		,Rarity: "Uncommon"
	}
	,{
		 Type: "Head"
		,Name: "Chain_Coif"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 10
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 14
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Chain Coif\n\nDefense +14\nCooldown Reduction +10%"
		,Rarity: "Uncommon"
	}
	,{
		 Type: "Head"
		,Name: "Safety_Helmet"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 210
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Safety Helmet\n\nMax HP +210"
		,Rarity: "Uncommon"
	}
	,{
		 Type: "Head"
		,Name: "Ballistic_Helmet"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 8
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 15
		,Max_HP: 90
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Ballistic Helmet\n\nDefense +15\nMax HP +90\nCooldown Reduction +8%"
		,Rarity: "Rare"
	}
	,{
		 Type: "Head"
		,Name: "Fire_Helmet"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 280
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Fire Helmet\n\nMax HP +280"
		,Rarity: "Rare"
	}
	,{
		 Type: "Head"
		,Name: "Tiara"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 14
		,Max_HP: 0
		,Max_SP: 460
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Tiara\n\nDefense +14\nMax SP +460"
		,Rarity: "Rare"
	}
	,{
		 Type: "Head"
		,Name: "Crown"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 8
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 16
		,Max_HP: 0
		,Max_SP: 360
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Crown\n\nDefense +16\nMax SP +360\nSkill Amplification +8%"
		,Rarity: "Rare"
	}
	,{
		 Type: "Head"
		,Name: "Close_Helm"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 10
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 20
		,Max_HP: 0
		,Max_SP: 130
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Close Helm\n\nDefense +20\nMax SP +130\nMovement Speed +0.1\nCooldown Reduction +10%"
		,Rarity: "Rare"
	}
	,{
		 Type: "Head"
		,Name: "Motorcycle_Helmet"
		,Attack_Power: 10
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 300
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 2.5
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Motorcycle Helmet\n\nAttack Power +10\nMax HP +300\nVision Range +2.5"
		,Rarity: "Rare"
	}
	,{
		 Type: "Head"
		,Name: "Mithril_Helm"
		,Attack_Power: 0
		,Attack_Speed: 12
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 15
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 38
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.2
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Mithril Helm\n\nDefense +38\nAttack Speed +12%\nMovement Speed +0.2\nCooldown Reduction +15%"
		,Rarity: "Epic"
	}
	,{
		 Type: "Head"
		,Name: "Crystal_Tiara"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 22
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 14
		,Max_HP: 0
		,Max_SP: 700
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Crystal Tiara\n\nDefense +14\nMax SP +700\nCritical Strike Chance +22%"
		,Rarity: "Epic"
	}
	,{
		 Type: "Head"
		,Name: "Tactical_OPS_Helmet"
		,Attack_Power: 0
		,Attack_Speed: 20
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 15
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 15
		,Max_HP: 120
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Tactical OPS Helmet\n\nDefense +15\nMax HP +120\nAttack Speed +20%\nCooldown Reduction +15%"
		,Rarity: "Epic"
	}
	,{
		 Type: "Head"
		,Name: "Helm_of_Banneret"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 10
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 11
		,Defense: 20
		,Max_HP: 0
		,Max_SP: 200
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Helm of Banneret\n\nDefense +20\nMax SP +200\nMovement Speed +0.1\nCooldown Reduction +10%\nSkill Damage Reduction +11%"
		,Rarity: "Epic"
	}
	,{
		 Type: "Head"
		,Name: "Imperial_Crown"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 8
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 18
		,Max_HP: 300
		,Max_SP: 500
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Imperial Crown\n\nDefense +18\nMax HP +300\nMax SP +500\nSkill Amplification +8%"
		,Rarity: "Epic"
	}
	,{
		 Type: "Head"
		,Name: "Imperial_Burgonet"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 16
		,Cooldown_Reduction: 10
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 10
		,Max_HP: 0
		,Max_SP: 200
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Imperial Burgonet\n\nDefense +10\nMax SP +200\nMovement Speed +0.1\nCooldown Reduction +10%\nSkill Amplification +16%"
		,Rarity: "Epic"
	}
	,{
		 Type: "Head"
		,Name: "Chinese_Opera_Mask"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 22
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 16
		,Max_HP: 0
		,Max_SP: 300
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.1
		,Out_of_Combat_Movement_Speed: 0.4
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Chinese Opera Mask\n\nDefense +16\nMax SP +300\nMovement Speed +0.1\nLife Steal +22%\nMovement speed while not in combat +0.4"
		,Rarity: "Epic"
	}
	,{
		 Type: "Head"
		,Name: "Laurel_Wreath"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 15
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 2
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 18
		,Max_HP: 0
		,Max_SP: 580
		,HP_Regen: 1.5
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
		,Title: "Laurel Wreath\n\nDefense +18\nMax SP +580\nHP Regen +1.5\nSP Regen +2\nExtra Normal Attack Damage +15"
		,Rarity: "Legendary"
	}
];