let chests = [
	{
		 Type: "Chest"
		,Name: "Windbreaker"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 50
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 3
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Monk`s_Robe"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 5
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 5
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Full_Body_Swimsuit"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 5
		,Defense: 1
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 3
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Fabric_Armor"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 11
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Leather_Armor"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 22
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Leather_Jacker"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 8
		,Max_HP: 70
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 6
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Turtle_Dobok"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 10
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 10
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Military_Suit"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 50
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 10
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Patched_Robe"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 7
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 5
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 1
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 3
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Dress"
		,Attack_Power: 8
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 100
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 8
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Bikini"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 11
		,Defense: 4
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Diving_Suit"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 10
		,Defense: 9
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Rider_Jacket"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 11
		,Max_HP: 70
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 9
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Chain_Armor"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 30
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Suit"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 5
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 12
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Qipao"
		,Attack_Power: 10
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 150
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 10
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Sheet_Metal_Armor"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 38
		,Max_HP: 100
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: -0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Hanbok"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 15
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 5
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 1
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Bulletproof_Vest"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 10
		,Max_HP: 130
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 10
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Sunset_Armor"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 28
		,Max_HP: 450
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Covert_Agent_Uniform"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 15
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 23
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 2.5
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Optical_Camouflage_Suit"
		,Attack_Power: 10
		,Attack_Speed: 0
		,Critical_Strike_Chance: 22
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 10
		,Defense: 20
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Rocker`s_Jacket"
		,Attack_Power: 30
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 11
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 15
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0.3
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Mithril_Armor"
		,Attack_Power: 0
		,Attack_Speed: 12
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 65
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.2
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Crusader_Armor"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 20
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 30
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 200
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: -0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Amazoness_Armor"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 20
		,Defense: 28
		,Max_HP: 120
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Dragon_Dobok"
		,Attack_Power: 11
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 10
		,SP_Regen: 0
		,SP_Regen_Percent: 150
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 10
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 3
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 1
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Commander`s_Armor"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 16
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 20
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Butler`s_Suit"
		,Attack_Power: 30
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 20
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 10
		,Move_Speed: 0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Battle_Suit"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 12
		,Defense: 25
		,Max_HP: 140
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 12
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "EOD_Suit"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 10
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 15
		,Max_HP: 300
		,Max_SP: 0
		,HP_Regen: 1
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 10
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Blazing_Dress"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 22
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 3
		,SP_Regen_Percent: 75
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 25
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 2.5
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Kabana"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 18
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 36
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Chest"
		,Name: "Queen_of_Hearts"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 25
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 45
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 3
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
];
let heads = [
	{
		 Type: "Head"
		,Name: "Hairband"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 4
		,Max_HP: 0
		,Max_SP: 130
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Hat"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 5
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 4
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Bike_Helmet"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 90
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Mask"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 10
		,Max_HP: 0
		,Max_SP: 130
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.08
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Circlet"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 14
		,Max_HP: 0
		,Max_SP: 270
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Beret"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 13
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 5
		,Max_HP: 50
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Chain_Coif"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 10
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 14
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Safety_Helmet"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 210
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Ballistic_Helmet"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 13
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 10
		,Max_HP: 90
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Fire_Helmet"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 280
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Tiara"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 14
		,Max_HP: 0
		,Max_SP: 460
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Crown"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 11
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 16
		,Max_HP: 0
		,Max_SP: 360
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Close_Helm"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 10
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 20
		,Max_HP: 0
		,Max_SP: 130
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Motorcycle_Helmet"
		,Attack_Power: 10
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 300
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 2.5
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Crystal_Tiara"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 22
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 14
		,Max_HP: 0
		,Max_SP: 700
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Mithril_Helm"
		,Attack_Power: 0
		,Attack_Speed: 12
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 15
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 38
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.2
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Tactical_OPS_Helmet"
		,Attack_Power: 0
		,Attack_Speed: 20
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 15
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 15
		,Max_HP: 120
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Helm_of_Banneret"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 10
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 11
		,Defense: 20
		,Max_HP: 0
		,Max_SP: 200
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Chinese_Opera_Mask"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 22
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 16
		,Max_HP: 0
		,Max_SP: 300
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.1
		,Out_of_Combat_Movement_Speed: 0.4
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Imperial_Crown"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 10
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 18
		,Max_HP: 300
		,Max_SP: 500
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Imperial_Burgonet"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 14
		,Cooldown_Reduction: 10
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 10
		,Max_HP: 0
		,Max_SP: 200
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Head"
		,Name: "Laurel_Wreath"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 15
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 2
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 18
		,Max_HP: 0
		,Max_SP: 580
		,HP_Regen: 1.5
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
];
let arms = [
	{
		 Type: "Arm"
		,Name: "Watch"
		,Attack_Power: 0
		,Attack_Speed: 10
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Bandage"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0.8
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Bracelet"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 220
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Leather_Shield"
		,Attack_Power: 10
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 10
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Squad_Leader_Armband"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 15
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 1.5
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Bracer"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 13
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 1
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Sheath"
		,Attack_Power: 18
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 2
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Golden_Bracelet"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 12
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 220
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Bazuband"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 25
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 8
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Crimson_Bracelet"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 200
		,Max_SP: 250
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Steel_Shield"
		,Attack_Power: 23
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 25
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: -0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Cube_Watch"
		,Attack_Power: 0
		,Attack_Speed: 50
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 27
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Sword_Stopper"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 26
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 11
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Mithril_Shield"
		,Attack_Power: 30
		,Attack_Speed: 12
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 30
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Vital_Sign_Sensor"
		,Attack_Power: 0
		,Attack_Speed: 30
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 15
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Creed_of_the_Knight"
		,Attack_Power: 30
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 20
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 25
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 1.5
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: -0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Sword_of_Shah_Jahan"
		,Attack_Power: 28
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 350
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 2
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Draupnir"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 15
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 10
		,Max_HP: 0
		,Max_SP: 240
		,HP_Regen: 1
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Bracelet_of_Skadi"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 20
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 2
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 200
		,Max_SP: 250
		,HP_Regen: 2
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Radar"
		,Attack_Power: 0
		,Attack_Speed: 35
		,Critical_Strike_Chance: 20
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 15
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Arm"
		,Name: "Auto-arms"
		,Attack_Power:40
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 35
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 1.5
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
];
let legs = [
	{
		 Type: "Leg"
		,Name: "Slippers"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0.5
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.04
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Running_Shoes"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.08
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Tights"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 5
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.04
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Knee_Pads"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 8
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.16
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Chain_Leggings"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 10
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.14
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "High_Heels"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0.8
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.17
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Heelys"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.12
		,Out_of_Combat_Movement_Speed: 0.2
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Repaired_Slippers"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0.5
		,SP_Regen_Percent: 30
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.16
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Boots"
		,Attack_Power: 0
		,Attack_Speed: 2
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0.6
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.22
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Steel_Knee_Pads"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 20
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.24
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Straitjacket_Sneakers"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 10
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0.7
		,SP_Regen_Percent: 50
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.35
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Maverick_Runner"
		,Attack_Power: 0
		,Attack_Speed: 15
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.25
		,Out_of_Combat_Movement_Speed: 0.5
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Combat_Boots"
		,Attack_Power: 0
		,Attack_Speed: 7
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0.6
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.27
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Killer_Heels"
		,Attack_Power: 5
		,Attack_Speed: 0
		,Critical_Strike_Chance: 10
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0.8
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.16
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Feather_Boots"
		,Attack_Power: 0
		,Attack_Speed: 30
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 1
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.4
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Mithril_Boots"
		,Attack_Power: 0
		,Attack_Speed: 12
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 22
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.45
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Bucephalus"
		,Attack_Power: 5
		,Attack_Speed: 0
		,Critical_Strike_Chance: 17
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 1
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 5
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.33
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "White_Rhinos"
		,Attack_Power: 0
		,Attack_Speed: 15
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0.7
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.35
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "EOD_Boots"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 23
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 1
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.33
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Red_Shoes"
		,Attack_Power: 5
		,Attack_Speed: 0
		,Critical_Strike_Chance: 10
		,Critical_Strike_Damage: 0
		,Life_Steal: 15
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 1
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.4
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Glacial_Shoes"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 15
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 2
		,SP_Regen_Percent: 60
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 2
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.15
		,Out_of_Combat_Movement_Speed: 0.5
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Leg"
		,Name: "Boots_of_Hermes"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 40
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.4
		,Out_of_Combat_Movement_Speed: 0.2
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
];
let accessorys = [
	{
		 Type: "Accessory"
		,Name: "Feather"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.08
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Flower"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 9
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Ribbon"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 5
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Fan"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 11
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Buddhist_Scripture"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 7
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Box"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 90
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Holy_Grail"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 120
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Cross"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 7
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Binoculars"
		,Attack_Power: 2
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 1.5
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Gilded_Quill_Fan"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 14
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Saint`s_Relic"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 8
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 150
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Flower_of_Fate"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 15
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 10
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Glass_Pieces"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 13
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Doll"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 11
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 100
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Sniping_Scope"
		,Attack_Power: 6
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 4
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Buddha_Sarira"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 7
		,Cooldown_Reduction: 10
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Quiver"
		,Attack_Power: 0
		,Attack_Speed: 22
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Feather_Duster"
		,Attack_Power: 9
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Powder_of_Life"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 1.5
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 1.5
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Uchiwa"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 15
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 21
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 100
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Magazine"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 350
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 6
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Moonlight_Pendant"
		,Attack_Power: 20
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 20
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Schrodinger`s_Box"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 7
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 420
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Veritas_Lux_Mea"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 12
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 8
		,Cooldown_Reduction: 10
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 150
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "White_Crane_Fan"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 16
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Laced_Quiver"
		,Attack_Power: 10
		,Attack_Speed: 25
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0.1
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Glacial_Ice"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 18
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 1.5
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 1.5
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "True_Samadhi_Fire"
		,Attack_Power: 0
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 13
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 1.5
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 1.5
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
	,{
		 Type: "Accessory"
		,Name: "Emerald_Tablet"
		,Attack_Power: 10
		,Attack_Speed: 0
		,Critical_Strike_Chance: 15
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 10
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 10
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 0
		,Atk_Speed: 0
	}
];