const Glove = [
    {
         Type: "Glove"
        ,Name: "Brass_Knuckles"
        ,Attack_Power: 10
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Brass Knuckles\n\nAttack Power +10"
        ,Rarity: "Common"
    }
    ,{
         Type: "Glove"
        ,Name: "Cotton_Gloves"
        ,Attack_Power: 7
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Cotton Gloves\n\nAttack Power +7"
        ,Rarity: "Common"
    }
    ,{
         Type: "Glove"
        ,Name: "Leather_Gloves"
        ,Attack_Power: 18
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Leather Gloves\n\nAttack Power +18"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Glove"
        ,Name: "Iron_Knuckles"
        ,Attack_Power: 20
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Iron Knuckles\n\nAttack Power +20"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Glove"
        ,Name: "Gauntlet"
        ,Attack_Power: 32
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: -0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Gauntlet\n\nAttack Power +32\nMovement Speed -0.1"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Glove"
        ,Name: "Wing_Knuckles"
        ,Attack_Power: 20
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Wing Knuckles\n\nAttack Power +20\nMovement Speed +0.1"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Glove"
        ,Name: "Bone_Gauntlet"
        ,Attack_Power: 35
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 13
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: -0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Bone Gauntlet\n\nAttack Power +35\nDefense +13\nMovement Speed -0.1"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Glove"
        ,Name: "Shatter_Shell_Gauntlet"
        ,Attack_Power: 32
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 15
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: -0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Shatter Shell Gauntlet\n\nAttack Power +32\nMovement Speed -0.1\nExtra Normal Attack Damage +15"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Glove"
        ,Name: "Glass_Knuckles"
        ,Attack_Power: 28
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 10
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Glass Knuckles\n\nAttack Power +28\nCritical Strike Chance +10%"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Glove"
        ,Name: "Phoenix_Gloves"
        ,Attack_Power: 27
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 30
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Phoenix Gloves\n\nAttack Power +27\nSkill Amplification +30"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Glove"
        ,Name: "One_Inch_Punch"
        ,Attack_Power: 50
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 10
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 50
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 25
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "One Inch Punch\n\nAttack Power +50\nDefense +25\nSP Regen +50%\nLife Steal +10%"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Glove"
        ,Name: "Divine_Fist"
        ,Attack_Power: 46
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 33
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: -0.05
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Divine Fist\n\nAttack Power +46\nMovement Speed -0.05\nExtra Normal Attack Damage +33"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Glove"
        ,Name: "Bloodwing_Knuckles"
        ,Attack_Power: 53
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 250
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Bloodwing Knuckles\n\nAttack Power +53\nMax HP +250\nMovement Speed +0.1"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Glove"
        ,Name: "Frost_Petal_Hand"
        ,Attack_Power: 27
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 38
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 15
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Frost Petal Hand\n\nAttack Power +27\nCooldown Reduction +15%\nSkill Amplification +38"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Glove"
        ,Name: "Buddha`s_Palm"
        ,Attack_Power: 33
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 18
        ,Cooldown_Reduction: 10
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Buddha`s Palm\n\nAttack Power +33\nCooldown Reduction +10%\nSkill Amplification +18%"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Glove"
        ,Name: "Brasil_Gauntlet"
        ,Attack_Power: 48
        ,Attack_Speed: 30
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 13
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 1
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: -0.05
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Brasil Gauntlet\n\nAttack Power +48\nDefense +13\nHP Regen +1\nAttack Speed +30%\nMovement Speed -0.05"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Glove"
        ,Name: "White_Claw_Punch"
        ,Attack_Power: 55
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 20
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "White Claw Punch\n\nAttack Power +55\nCritical Strike Chance +20%"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Glove"
        ,Name: "Imperial_Silk_Gloves"
        ,Attack_Power: 85
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 0.85
        ,Atk_Speed: 0.63
        ,Title: "Imperial Silk Gloves\n\nAttack Power +85\nMovement Speed +0.1"
        ,Rarity: "Epic"
    }
];