const guitar = [
	{
		 Type: "Guitar"
		,Name: "Starter_Guitar"
		,Attack_Power: 5
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "Starter Guitar\n\nAttack Power +5"
		,Rarity: "Common"
	}
	,{
		 Type: "Guitar"
		,Name: "Golden_Bridge"
		,Attack_Power: 8
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 14
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "Golden Bridge\n\nAttack Power +8\nSkill Amplification +14%"
		,Rarity: "Uncommon"
	}
	,{
		 Type: "Guitar"
		,Name: "Single_Coil_Pickup"
		,Attack_Power: 8
		,Attack_Speed: 15
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 2
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "Single Coil Pickup\n\nAttack Power +8\nAttack Speed +15%\nExtra Normal Attack Damage +2"
		,Rarity: "Uncommon"
	}
	,{
		 Type: "Guitar"
		,Name: "Ruby_Special"
		,Attack_Power: 20
		,Attack_Speed: 20
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 2
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 300
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "Ruby Special\n\nAttack Power +20\nMax HP +300\nAttack Speed +20%\nExtra Normal Attack Damage +2"
		,Rarity: "Rare"
	}
	,{
		 Type: "Guitar"
		,Name: "Humbucker_Pickup"
		,Attack_Power: 25
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 15
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 3
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "Humbucker Pickup\n\nAttack Power +25\nVision Range +3\nSkill Amplification +15%"
		,Rarity: "Rare"
	}
	,{
		 Type: "Guitar"
		,Name: "King-V"
		,Attack_Power: 13
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 16
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "King-V\n\nAttack Power +13\nSkill Amplification +16%"
		,Rarity: "Rare"
	}
	,{
		 Type: "Guitar"
		,Name: "Nocaster"
		,Attack_Power: 15
		,Attack_Speed: 20
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 10
		,Extra_Normal_Attack_Damage: 10
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "Nocaster\n\nAttack Power +15\nAttack Speed +20%\nLife Steal +10%\nExtra Normal Attack Damage +10"
		,Rarity: "Rare"
	}
	,{
		 Type: "Guitar"
		,Name: "Superstrat"
		,Attack_Power: 19
		,Attack_Speed: 15
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 2
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "Superstrat\n\nAttack Power +19\nAttack Speed +15%\nExtra Normal Attack Damage +2"
		,Rarity: "Rare"
	}
	,{
		 Type: "Guitar"
		,Name: "Wild_Horse"
		,Attack_Power: 9
		,Attack_Speed: 25
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 6
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "Wild Horse\n\nAttack Power +9\nAttack Speed +25%\nExtra Normal Attack Damage +6"
		,Rarity: "Rare"
	}
	,{
		 Type: "Guitar"
		,Name: "Bohemian"
		,Attack_Power: 50
		,Attack_Speed: 20
		,Critical_Strike_Chance: 20
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 2
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 380
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "Bohemian\n\nAttack Power +50\nMax HP +380\nAttack Speed +20%\nCritical Strike Chance +20%\nExtra Normal Attack Damage +2"
		,Rarity: "Epic"
	}
	,{
		 Type: "Guitar"
		,Name: "Stairway_to_Heaven"
		,Attack_Power: 52
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 20
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 200
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 4
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "Stairway to Heaven\n\nAttack Power +52\nHP Regen +200%\nVision Range +4\nSkill Amplification +20%"
		,Rarity: "Epic"
	}
	,{
		 Type: "Guitar"
		,Name: "Purple_Haze"
		,Attack_Power: 85
		,Attack_Speed: 0
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 0
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 19
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "Purple Haze\n\nAttack Power +85\nSkill Amplification +19%"
		,Rarity: "Epic"
	}
	,{
		 Type: "Guitar"
		,Name: "Satisfaction"
		,Attack_Power: 30
		,Attack_Speed: 30
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 10
		,Extra_Normal_Attack_Damage: 11
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "Satisfaction\n\nAttack Power +30\nAttack Speed +30%\nLife Steal +10%\nExtra Normal Attack Damage +11"
		,Rarity: "Epic"
	}
	,{
		 Type: "Guitar"
		,Name: "Wonderful_Tonight"
		,Attack_Power: 100
		,Attack_Speed: 45
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 2
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "Wonderful Tonight\n\nAttack Power +100\nAttack Speed +45%\nExtra Normal Attack Damage +2"
		,Rarity: "Epic"
	}
	,{
		 Type: "Guitar"
		,Name: "The_Wall"
		,Attack_Power: 70
		,Attack_Speed: 18
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 2
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "The Wall\n\nAttack Power +70\nAttack Speed +18%\nExtra Normal Attack Damage +2"
		,Rarity: "Epic"
	}
	,{
		 Type: "Guitar"
		,Name: "Teen_Spirit"
		,Attack_Power: 10
		,Attack_Speed: 25
		,Critical_Strike_Chance: 0
		,Critical_Strike_Damage: 0
		,Life_Steal: 0
		,Extra_Normal_Attack_Damage: 20
		,Extra_Normal_Attack_Damage_Percent: 0
		,Skill_Amplification: 0
		,Skill_Amplification_Percent: 0
		,Cooldown_Reduction: 0
		,SP_Regen: 0
		,SP_Regen_Percent: 0
		,Skill_Damage_Reduction: 0
		,Skill_Damage_Reduction_Percent: 0
		,Defense: 0
		,Max_HP: 0
		,Max_SP: 0
		,HP_Regen: 0
		,HP_Regen_Percent: 0
		,Normal_Attack_Damage_Reduction: 0
		,Move_Speed: 0
		,Out_of_Combat_Movement_Speed: 0
		,Vision_Range: 0
		,Attack_Range: 0
		,Base_Range: 3.85
		,Atk_Speed: 0.43
		,Title: "Teen Spirit\n\nAttack Power +10\nAttack Speed +25%\nExtra Normal Attack Damage +20"
		,Rarity: "Epic"
	}
];