const Spear = [
    {
         Type: "Spear"
        ,Name: "Short_Spear"
        ,Attack_Power: 15
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 2.15
        ,Atk_Speed: 0.445
        ,Title: "Short Spear\n\nAttack Power +15"
        ,Rarity: "Common"
    }
    ,{
         Type: "Spear"
        ,Name: "Bamboo_Spear"
        ,Attack_Power: 37
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 2.15
        ,Atk_Speed: 0.445
        ,Title: "Bamboo Spear\n\nAttack Power +37"
        ,Rarity: "Uncommon"
    }
    ,{
         Type: "Spear"
        ,Name: "Bident"
        ,Attack_Power: 52
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 2.15
        ,Atk_Speed: 0.445
        ,Title: "Bident\n\nAttack Power +52"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Spear"
        ,Name: "Pike"
        ,Attack_Power: 67
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: -0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 2.15
        ,Atk_Speed: 0.445
        ,Title: "Pike\n\nAttack Power +67\nMovement Speed -0.1"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Spear"
        ,Name: "Halberd_Axe"
        ,Attack_Power: 90
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: -0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 2.15
        ,Atk_Speed: 0.445
        ,Title: "Halberd Axe\n\nAttack Power +90\nMovement Speed -0.1"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Spear"
        ,Name: "Sharpened_Spear"
        ,Attack_Power: 40
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 2.15
        ,Atk_Speed: 0.445
        ,Title: "Sharpened Spear\n\nAttack Power +40\nMovement Speed +0.1"
        ,Rarity: "Rare"
    }
    ,{
         Type: "Spear"
        ,Name: "Gentian_Silver_Gun"
        ,Attack_Power: 105
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0.2
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 2.15
        ,Atk_Speed: 0.445
        ,Title: "Gentian Silver Gun\n\nAttack Power +105\nMovement Speed +0.2"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Spear"
        ,Name: "Eighteen_foot_spear"
        ,Attack_Power: 100
        ,Attack_Speed: 40
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 2.15
        ,Atk_Speed: 0.445
        ,Title: "Eighteen Foot Spear\n\nAttack Power +100\nMovement Speed +40%"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Spear"
        ,Name: "Cosmic_Bident"
        ,Attack_Power: 150
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 2.15
        ,Atk_Speed: 0.445
        ,Title: "Cosmic Bident\n\nAttack Power +150"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Spear"
        ,Name: "Lance_of_Poseidon"
        ,Attack_Power: 120
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: -0.05
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 2.15
        ,Atk_Speed: 0.445
        ,Title: "Lance of Poseidon\n\nAttack Power +120"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Spear"
        ,Name: "Fangtian_Huaji"
        ,Attack_Power: 88
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 31
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: -0.1
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 2.15
        ,Atk_Speed: 0.445
        ,Title: "Fangtian Huaji\n\nAttack Power +88\nMovement Speed -0.1\nSkill Amplification +31\n Healing Reduction (Skills) -40%"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Spear"
        ,Name: "Dragon_Guandao"
        ,Attack_Power: 130
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: -0.05
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 2.15
        ,Atk_Speed: 0.445
        ,Title: "Dragon Guandao\n\nAttack Power +130\nMovement Speed -0.05"
        ,Rarity: "Epic"
    }
    ,{
         Type: "Spear"
        ,Name: "Blazing_Lance"
        ,Attack_Power: 110
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 0
        ,Extra_Normal_Attack_Damage: 30
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 1.5
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 1.5
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 2.15
        ,Atk_Speed: 0.445
        ,Title: "Blazing Lance\n\nAttack Power +110\nHP Regen +1.5\nSP Regen +1.5\nExtra Normal Attack Damage +30"
        ,Rarity: "Legendary"
    }
    ,{
         Type: "Spear"
        ,Name: "Spear_of_Longinus"
        ,Attack_Power: 150
        ,Attack_Speed: 0
        ,Critical_Strike_Chance: 0
        ,Critical_Strike_Damage: 0
        ,Life_Steal: 20
        ,Extra_Normal_Attack_Damage: 0
        ,Extra_Normal_Attack_Damage_Percent: 0
        ,Skill_Amplification: 0
        ,Skill_Amplification_Percent: 0
        ,Cooldown_Reduction: 0
        ,SP_Regen: 0
        ,SP_Regen_Percent: 0
        ,Skill_Damage_Reduction: 0
        ,Skill_Damage_Reduction_Percent: 0
        ,Defense: 0
        ,Max_HP: 0
        ,Max_SP: 0
        ,HP_Regen: 0
        ,HP_Regen_Percent: 0
        ,Normal_Attack_Damage_Reduction: 0
        ,Move_Speed: 0
        ,Out_of_Combat_Movement_Speed: 0
        ,Vision_Range: 0
        ,Attack_Range: 0
        ,Base_Range: 2.15
        ,Atk_Speed: 0.445
        ,Title: "Spear of Longinus\n\nAttack Power +140\nLife Steal +20%"
        ,Rarity: "Legendary"
    }
];